Document: glbindify
Title: Debian glbindify Manual
Author: <insert document author here>
Abstract: This manual describes what glbindify is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/glbindify/glbindify.sgml.gz

Format: postscript
Files: /usr/share/doc/glbindify/glbindify.ps.gz

Format: text
Files: /usr/share/doc/glbindify/glbindify.text.gz

Format: HTML
Index: /usr/share/doc/glbindify/html/index.html
Files: /usr/share/doc/glbindify/html/*.html
